# Generated by Django 5.1.6 on 2025-09-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('375ml', '375ml Bottle'), ('500ml', '500ml Bottle'), ('750ml', '750ml Bottle'), ('1L', '1L Bottle'), ('1.5L', '1.5L Bottle'), ('3L', '3L Bottle')], max_length=20),
        ),
    ]
