# Generated by Django 5.1.6 on 2025-09-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0004_remove_customuser_address_remove_customuser_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('whisky', 'Whisky'), ('vodka', 'Vodka'), ('beer', 'Beer'), ('wine', 'Wine'), ('rum', 'Rum'), ('gin', 'Gin'), ('tequila', 'Tequila')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
