# Generated by Django 5.1.6 on 2025-09-08 09:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0007_customuser_raw_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('offer_type', models.CharField(choices=[('today', "Today's Offer"), ('combo', 'Combo Offer'), ('discount', 'Discount Offer'), ('special', 'Special Day Offer')], max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('combo_offers', models.ManyToManyField(blank=True, to='wine.combooffer')),
                ('products', models.ManyToManyField(blank=True, to='wine.product')),
            ],
        ),
    ]
