# Generated by Django 5.1.12 on 2025-11-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0008_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
