# Generated by Django 5.1.12 on 2025-11-26 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0009_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wine.offer'),
        ),
    ]
