# Generated by Django 5.1.12 on 2025-11-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0010_cartitem_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Home Delivery'), ('pickup', 'Pickup from Store'), ('instore_cash', 'In-Store Cash Purchase')], default='delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('cash', 'Cash'), ('online', 'Online Payment')], default='online', max_length=50),
        ),
    ]
