# Generated by Django 5.1.12 on 2025-11-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0011_order_delivery_address_order_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='token_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Home Delivery'), ('pickup', 'Pickup from Store')], default='delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
